# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto\x12\x04\x61uth\"+\n\x18\x43heckUserExistingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xae\x01\n\x19\x43heckUserExistingResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x14\n\x0cis_superuser\x18\x05 \x01(\x08\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t2^\n\x04\x41uth\x12V\n\x11\x43heckUserExisting\x12\x1e.auth.CheckUserExistingRequest\x1a\x1f.auth.CheckUserExistingResponse\"\x00\x42\x08Z\x06./authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\006./auth'
    _globals['_CHECKUSEREXISTINGREQUEST']._serialized_start = 20
    _globals['_CHECKUSEREXISTINGREQUEST']._serialized_end = 63
    _globals['_CHECKUSEREXISTINGRESPONSE']._serialized_start = 66
    _globals['_CHECKUSEREXISTINGRESPONSE']._serialized_end = 240
    _globals['_AUTH']._serialized_start = 242
    _globals['_AUTH']._serialized_end = 336
# @@protoc_insertion_point(module_scope)
