# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11transaction.proto\x12\x0btransaction\"+\n\x18\x43reateUserBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\'\n\x19\x43reateUserBalanceResponse\x12\n\n\x02id\x18\x01 \x01(\t2s\n\x0bTransaction\x12\x64\n\x11\x43reateUserBalance\x12%.transaction.CreateUserBalanceRequest\x1a&.transaction.CreateUserBalanceResponse\"\x00\x42\x0fZ\r./transactionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\r./transaction'
    _globals['_CREATEUSERBALANCEREQUEST']._serialized_start = 34
    _globals['_CREATEUSERBALANCEREQUEST']._serialized_end = 77
    _globals['_CREATEUSERBALANCERESPONSE']._serialized_start = 79
    _globals['_CREATEUSERBALANCERESPONSE']._serialized_end = 118
    _globals['_TRANSACTION']._serialized_start = 120
    _globals['_TRANSACTION']._serialized_end = 235
# @@protoc_insertion_point(module_scope)
